events {}

http {

    # upstream = backend servers
    # similar to target group in AWS ALB
    upstream backend_servers {

        server nginx1:80;
        server nginx2:80;

    }

    server {

        listen 80;

        location / {

            # forward request to backend servers
            proxy_pass http://backend_servers;

        }

    }

}